# Copyright (c) 2023 Sebastien Lemetter
# makefile for writer.c
# Available commands: make and make clean
# ========================================== 

# Executing make with no argument will execute the first command only
writermake: writer.c
	gcc -g -Wall -o writer.o writer.c

.PHONY: clean

clean:
	rm -f *.o writer